[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_build.partitions = default.csv
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=1

lib_deps =
  adafruit/Adafruit LED Backpack Library @ ^1.5.1
  adafruit/Adafruit GFX Library @ ^1.12.1
  adafruit/Adafruit BusIO @ ^1.17.0
  h2zero/NimBLE-Arduino @ ^1.4.3
  bblanchon/ArduinoJson @ ^7.3.0
